// The wire protocol has three implementations - the self-host server in Rust,
// this Lambda, and the browser that mints the link - and two of them have to
// produce the same pairing code from the same token or a person eye-matching
// the terminal against the portal is told the truth is a mismatch. Nothing in
// the type system holds them together, so this does: the vectors below are
// generated by the Rust implementation (server/src/board.rs), asserted here
// against the Lambda's, asserted in server/tests/pairing.rs against Rust's,
// and asserted in site/tests/portal.spec.js against the browser's.
//
//   npm test          (from the repo root)
//
// It imports protocol.ts directly: Node strips the types itself, so there is
// no build step between the code that ships and the code under test.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import {
  DAY_RETENTION_SECONDS, dayRollups, diffEndings, etimeSeconds, isStale, newSecret, packSnapshot,
  pairingCode, previousOf, sha256Hex, trimToBudget, unpackSnapshot,
} from './protocol.ts';

/* ── the cross-implementation vectors ───────────────────────────────── */

// Generated by server/src/board.rs pairing_code. Do not edit to make a test
// pass: if these change, the Rust server and this Lambda have diverged and
// the enrollment handshake is broken.
export const PAIRING_VECTORS = [
  ['', 'FRM-2XH'],
  ['a', 'CY4-X6K'],
  ['tokenhud', 'K63-CWT'],
  ['DdI0kK2mBcCLpCoOtdgKrHRVJnUCLZbXDDvKfdG-P9k', 'C3D-3TH'],
  ['x'.repeat(43), 'DMA-8SQ'],
];

test('the pairing code matches the Rust implementation byte for byte', () => {
  for (const [token, expected] of PAIRING_VECTORS) {
    assert.equal(pairingCode(token), expected, `token ${JSON.stringify(token)}`);
  }
});

test('the pairing alphabet cannot be read two ways', () => {
  const codes = PAIRING_VECTORS.map(([t]) => pairingCode(t)).join('');
  for (const ambiguous of ['0', 'O', '1', 'I', 'L', 'U']) {
    assert.ok(!codes.includes(ambiguous), `${ambiguous} is ambiguous read aloud`);
  }
  assert.match(pairingCode('anything'), /^[A-Z2-9]{3}-[A-Z2-9]{3}$/);
});

test('sha256Hex matches the server hash the store is keyed on', () => {
  // echo -n "" | shasum -a 256
  assert.equal(
    sha256Hex(''),
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  );
});

test('secrets have the shape the agent and server both validate', () => {
  for (let i = 0; i < 32; i++) {
    const s = newSecret();
    // The agent's claim endpoint validates 20..=100; the server mints 43.
    assert.equal(s.length, 43);
    assert.match(s, /^[A-Za-z0-9_-]+$/, 'base64url, so it survives a URL fragment');
  }
  assert.notEqual(newSecret(), newSecret());
});

/* ── staleness: the spool-replay guard ──────────────────────────────── */

const at = (iso) => ({ collectedAt: iso });

test('a reading older than the stored one is stale', () => {
  assert.equal(isStale(at('2026-08-24T10:00:00Z'), at('2026-08-24T11:00:00Z'), null), true);
});

test('a reading newer than the stored one is not stale', () => {
  assert.equal(isStale(at('2026-08-24T12:00:00Z'), at('2026-08-24T11:00:00Z'), null), false);
});

test('a replayed duplicate of the stored reading is stale', () => {
  const same = '2026-08-24T11:00:00Z';
  assert.equal(isStale(at(same), at(same), null), true);
});

test('the first reading a machine ever sends is never stale', () => {
  assert.equal(isStale(at('2026-08-24T10:00:00Z'), null, null), false);
});

test('an unparseable timestamp is not treated as stale', () => {
  // Refusing the reading would lose data over a clock the agent formats; the
  // failure mode of accepting it is a reordered panel, not a silent gap.
  assert.equal(isStale(at('not a date'), at('2026-08-24T11:00:00Z'), null), false);
  assert.equal(isStale(at('2026-08-24T11:00:00Z'), {}, null), false);
});

test('lastSeenAt stands in when the stored snapshot has no timestamp', () => {
  assert.equal(isStale(at('2026-08-24T10:00:00Z'), {}, '2026-08-24T11:00:00Z'), true);
});

/* ── endings: what stopped between two readings ─────────────────────── */

const proc = (pid, cmd, elapsed = '00:05:00') => ({
  pid, cmd, tool: 'claude-code', kind: 'interactive', elapsed,
});
const snapWith = (procs, collectedAt = '2026-08-24T11:00:00Z') => ({
  collectedAt, metrics: { processes: procs },
});

test('a process gone from the next reading has ended', () => {
  const prev = snapWith([proc(1, 'claude a'), proc(2, 'claude b')], '2026-08-24T10:59:30Z');
  const cur = snapWith([proc(1, 'claude a')]);
  const out = diffEndings(prev, [], 'workbench', null, cur, '2026-08-24T11:00:00Z');
  assert.equal(out.length, 1);
  assert.equal(out[0].pid, 2);
  assert.equal(out[0].host, 'workbench');
  assert.equal(out[0].ran_seconds, 300);
  // Both timestamps, because the truth is a window, not an instant.
  assert.equal(out[0].last_seen, '2026-08-24T10:59:30Z');
  assert.equal(out[0].noticed_at, '2026-08-24T11:00:00Z');
});

test('a process still running has not ended', () => {
  const prev = snapWith([proc(1, 'claude a')]);
  const cur = snapWith([proc(1, 'claude a')]);
  assert.deepEqual(diffEndings(prev, [], 'w', null, cur, 'now'), []);
});

test('the first reading ends nothing', () => {
  const cur = snapWith([proc(1, 'claude a')]);
  assert.deepEqual(diffEndings(null, [], 'w', null, cur, 'now'), []);
});

test('endings accumulate newest-first and stay bounded at 40', () => {
  const kept = Array.from({ length: 40 }, (_, i) => ({ pid: 1000 + i }));
  const prev = snapWith([proc(7, 'claude gone')]);
  const out = diffEndings(prev, kept, 'w', null, snapWith([]), 'now');
  assert.equal(out.length, 40);
  assert.equal(out[0].pid, 7, 'the new ending leads');
  assert.equal(out[39].pid, 1038, 'the oldest fell off the end');
});

test('etime parses every ps shape the agent can send', () => {
  assert.equal(etimeSeconds('00:30'), 30);
  assert.equal(etimeSeconds('05:00'), 300);
  assert.equal(etimeSeconds('01:00:00'), 3600);
  assert.equal(etimeSeconds('2-03:04:05'), 2 * 86400 + 3 * 3600 + 4 * 60 + 5);
  assert.equal(etimeSeconds('nonsense'), null);
  assert.equal(etimeSeconds(undefined), null);
});

/* ── the size trim ──────────────────────────────────────────────────── */

test('a snapshot within budget is untouched and unmarked', () => {
  const snap = { metrics: { usage: { sessions: [1, 2, 3] } } };
  const out = trimToBudget(snap, 10_000);
  assert.deepEqual(out.metrics.usage.sessions, [1, 2, 3]);
  assert.equal(out.trimmed, undefined);
});

test('an oversized snapshot sheds sessions first and says it was trimmed', () => {
  const snap = {
    metrics: {
      usage: { sessions: Array.from({ length: 400 }, (_, i) => ({ id: 's'.repeat(50) + i })) },
      claude: { daily: [{ date: '2026-08-24' }] },
    },
  };
  const out = trimToBudget(snap, 2_000);
  assert.equal(out.trimmed, true);
  assert.equal(out.metrics.usage.sessions, undefined);
  assert.deepEqual(out.metrics.claude.daily, [{ date: '2026-08-24' }], 'cheaper sections survive');
});

test('trimming keeps going until it fits, not just one pass', () => {
  const fat = (n) => Array.from({ length: n }, (_, i) => ({ v: 'x'.repeat(80) + i }));
  const snap = {
    metrics: {
      usage: { sessions: fat(200), tools: { byTool: fat(200) } },
      prompts: fat(200),
      governance: { rules: fat(200) },
      codex: { sessions: fat(200) },
      claude: { daily: fat(200) },
    },
  };
  const out = trimToBudget(snap, 1_500);
  assert.ok(JSON.stringify(out).length <= 1_500, 'fits the budget it was given');
  assert.equal(out.trimmed, true);
});

/* ── packing: the reason a heartbeat is affordable ──────────────────── */

test('a reading survives being packed and unpacked exactly', () => {
  const snap = {
    host: 'workbench',
    collectedAt: '2026-08-24T11:00:00Z',
    // 1.1400000000000001 is the value the naive JSON parser produces for 1.14,
    // and the agent and the Rust server both go out of their way to round-trip
    // it correctly. A store that quietly changed it would undo that.
    metrics: { usage: { allTime: { estUSD: 1.14 } }, processes: [{ pid: 1, cmd: 'claude' }] },
  };
  assert.deepEqual(unpackSnapshot(packSnapshot(structuredClone(snap))), snap);
});

test('packing is what makes a reading small enough to be cheap', () => {
  // Readings are deeply repetitive, which is the property the write cost turns
  // on: a measured 94 KB reading packs to about 26 KB, and DynamoDB charges by
  // the kilobyte written.
  const day = (i) => ({ date: `2026-06-${String((i % 28) + 1).padStart(2, '0')}`, tokens: 1e6 + i, estUSD: 1.5, sessions: 3, toolCalls: 40, messages: 12 });
  const snap = { metrics: { claude: { daily: Array.from({ length: 300 }, (_, i) => day(i)) } } };
  const raw = JSON.stringify(snap).length;
  const packed = packSnapshot(snap).length;
  assert.ok(packed < raw / 4, `packed ${packed} should be far under raw ${raw}`);
});

test('a reading too big to pack is trimmed until it fits, and says so', () => {
  const fat = (n) => Array.from({ length: n }, (_, i) => ({ v: `${Math.random()}`.repeat(20) + i }));
  const snap = {
    metrics: {
      usage: { sessions: fat(400), tools: { byTool: fat(400) } },
      prompts: fat(400),
      governance: { rules: fat(400) },
      codex: { sessions: fat(400) },
      claude: { daily: fat(400) },
    },
  };
  const packed = packSnapshot(snap, 4_000);
  assert.ok(packed.length <= 4_000, `packed ${packed.length} fits the budget it was given`);
  assert.equal(unpackSnapshot(packed).trimmed, true);
});

test('an unreadable stored reading is null, not an exception', () => {
  // One corrupt row must not take down a board that has four other machines
  // on it.
  for (const bad of [null, undefined, '', 'not base64 gzip', 'AAAA']) {
    assert.equal(unpackSnapshot(bad), null);
  }
});

/* ── what the next heartbeat has to remember ────────────────────────── */

test('previousOf keeps exactly what the next diff reads, and nothing else', () => {
  const snap = {
    collectedAt: '2026-08-24T11:00:00Z',
    host: 'workbench',
    metrics: {
      processes: [{ pid: 1, cmd: 'claude', tool: 'claude-code', elapsed: '00:05:00' }],
      usage: { sessions: Array.from({ length: 500 }, (_, i) => i) },
    },
  };
  const prev = previousOf(snap);
  assert.deepEqual(Object.keys(prev).sort(), ['collectedAt', 'metrics']);
  assert.deepEqual(Object.keys(prev.metrics), ['processes']);
  assert.equal(prev.collectedAt, '2026-08-24T11:00:00Z');
  assert.ok(JSON.stringify(prev).length < 200, 'the expensive half did not come along');
});

test('the stub previousOf leaves behind still drives the two things that read it', () => {
  const first = { collectedAt: '2026-08-24T10:59:30Z', metrics: { processes: [{ pid: 2, cmd: 'claude b', tool: 'claude-code', elapsed: '00:05:00' }] } };
  const second = { collectedAt: '2026-08-24T11:00:00Z', metrics: { processes: [] } };
  const stub = previousOf(first);

  assert.equal(isStale(second, stub, null), false, 'a newer reading is not stale against the stub');
  assert.equal(isStale(first, stub, null), true, 'a replay of the stored reading is');

  const ended = diffEndings(stub, [], 'workbench', null, second, '2026-08-24T11:00:00Z');
  assert.equal(ended.length, 1);
  assert.equal(ended[0].pid, 2);
  assert.equal(ended[0].ran_seconds, 300);
  assert.equal(ended[0].last_seen, '2026-08-24T10:59:30Z');
});

test('previousOf survives a reading with no processes at all', () => {
  assert.deepEqual(previousOf({}), { collectedAt: null, metrics: { processes: [] } });
  assert.deepEqual(previousOf(null), { collectedAt: null, metrics: { processes: [] } });
});

/* ── the daily record ───────────────────────────────────────────────── */

// These rows outlive the reading they came from by more than a year, so what
// they are allowed to hold is a publishing decision rather than a storage one.
// The list below is the one `mergeEntries` already puts on a page strangers
// read, and the tests are here to make widening it deliberate.

const ONE_DAY_MS = 86_400_000;
const noon = (date) => Date.parse(`${date}T12:00:00Z`);

const aDay = (over = {}) => ({
  date: '2026-08-24',
  tokens: 1_234_567,
  estUSD: 4.5,
  sessions: 3,
  toolCalls: 88,
  messages: 12,
  byModel: { 'claude-sonnet-4-5': 1_000_000, 'gpt-5-codex': 234_567 },
  ...over,
});

test('a day rollup carries counts and nothing that names a machine or a project', () => {
  const [row] = dayRollups([aDay({
    // Everything a reading knows and a stored day may not repeat.
    host: 'workbench', project: '/Users/someone/secret-startup', branch: 'feature/acquisition',
    prompt: 'rewrite the pricing page', cwd: '/Users/someone', sessions_detail: ['s-1'],
  })], noon('2026-08-24'));

  assert.deepEqual(
    Object.keys(row).sort(),
    ['byModel', 'date', 'estUSD', 'messages', 'sessions', 'tokens', 'toolCalls', 'ttl'],
  );
  assert.equal(row.tokens, 1_234_567);
  assert.deepEqual(row.byModel, { 'claude-sonnet-4-5': 1_000_000, 'gpt-5-codex': 234_567 });
});

test('a day rollup holds nothing that could make two writes of it distinct', () => {
  // Idempotence is the point of the row: the agent re-derives the same ninety
  // days from disk every thirty seconds, so re-ingesting a day has to replace
  // it. The sort key is the date alone - but a row carrying an ingest time, a
  // sequence number or a run id would defeat that from the other side, by
  // making a second write of the same day a different item to compare.
  const [row] = dayRollups([aDay()], noon('2026-08-24'));
  for (const forbidden of ['collectedAt', 'ingestedAt', 'writtenAt', 'id', 'seq', 'installId']) {
    assert.equal(row[forbidden], undefined, `${forbidden} would make a day two rows`);
  }
  // Twice through, unchanged: nothing accumulates on the way past.
  const again = dayRollups([aDay()], noon('2026-08-24'));
  assert.deepEqual(again, dayRollups([aDay()], noon('2026-08-24')));
});

test('the retention window is measured from the day, not from the ingest', () => {
  // A backfill written today for a day three months ago must not buy that day
  // four hundred more days. Otherwise every heartbeat pushes the horizon out
  // and the window is not a window.
  const old = dayRollups([aDay({ date: '2026-06-01' })], noon('2026-08-24'))[0];
  assert.equal(old.ttl, Date.parse('2026-06-01T00:00:00Z') / 1000 + DAY_RETENTION_SECONDS);

  const later = dayRollups([aDay({ date: '2026-06-01' })], noon('2026-11-30'))[0];
  assert.equal(later.ttl, old.ttl, 'rewriting a day does not extend it');
});

test('a day already past the retention window is not written at all', () => {
  const day = aDay({ date: '2025-01-01' });
  const midnight = Date.parse('2025-01-01T00:00:00Z');

  assert.equal(dayRollups([day], midnight + 399 * ONE_DAY_MS).length, 1, 'still inside');
  assert.deepEqual(dayRollups([day], midnight + 401 * ONE_DAY_MS), [], 'written and swept is waste');
});

test('a day with no tokens is a day, not a missing day', () => {
  // Zero is a measurement: the agent ran, the machine was on, nobody used it.
  // Dropping the row would make that indistinguishable from a day the record
  // never had, and the streak on the board is counted off exactly this.
  const [row] = dayRollups([aDay({ tokens: 0, estUSD: 0, sessions: 0 })], noon('2026-08-24'));
  assert.equal(row.tokens, 0);
  assert.equal(row.estUSD, 0);
});

test('a count nobody reported is absent rather than zero', () => {
  const [row] = dayRollups([{ date: '2026-08-24', tokens: 10 }], noon('2026-08-24'));
  assert.equal(row.tokens, 10);
  assert.equal('estUSD' in row, false, 'unpriced and free are different facts');
  assert.equal('toolCalls' in row, false);
  assert.equal('byModel' in row, false, 'an empty map claims the models were counted');
});

test('a day that is not a date is not a day', () => {
  const junk = ['2026-8-4', '2026-13-45', 'yesterday', '', '2026-08-24T11:00:00Z', null];
  for (const date of junk) {
    assert.deepEqual(dayRollups([{ date, tokens: 5 }], noon('2026-08-24')), [], String(date));
  }
  assert.deepEqual(dayRollups(null), [], 'a reading with no days at all');
  assert.deepEqual(dayRollups({ '2026-08-24': 5 }), [], 'byDay is a list, not a map');
});

test('a per-model count that is not a number does not become one', () => {
  const [row] = dayRollups([aDay({
    byModel: { 'claude-sonnet-4-5': 1_000, unknown: null, broken: 'lots', '': 5 },
  })], noon('2026-08-24'));
  assert.deepEqual(row.byModel, { 'claude-sonnet-4-5': 1_000 });
});
