// The wire protocol has three implementations — the self-host server in Rust,
// this Lambda, and the browser that mints the link — and two of them have to
// produce the same pairing code from the same token or a person eye-matching
// the terminal against the portal is told the truth is a mismatch. Nothing in
// the type system holds them together, so this does: the vectors below are
// generated by the Rust implementation (server/src/board.rs), asserted here
// against the Lambda's, asserted in server/tests/pairing.rs against Rust's,
// and asserted in site/tests/portal.spec.js against the browser's.
//
//   npm test          (from the repo root)
//
// It imports protocol.ts directly: Node strips the types itself, so there is
// no build step between the code that ships and the code under test.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import {
  diffEndings, etimeSeconds, isStale, newSecret, packSnapshot, pairingCode, previousOf,
  sha256Hex, trimToBudget, unpackSnapshot,
} from './protocol.ts';

/* ── the cross-implementation vectors ───────────────────────────────── */

// Generated by server/src/board.rs pairing_code. Do not edit to make a test
// pass: if these change, the Rust server and this Lambda have diverged and
// the enrollment handshake is broken.
export const PAIRING_VECTORS = [
  ['', 'FRM-2XH'],
  ['a', 'CY4-X6K'],
  ['tokenhud', 'K63-CWT'],
  ['DdI0kK2mBcCLpCoOtdgKrHRVJnUCLZbXDDvKfdG-P9k', 'C3D-3TH'],
  ['x'.repeat(43), 'DMA-8SQ'],
];

test('the pairing code matches the Rust implementation byte for byte', () => {
  for (const [token, expected] of PAIRING_VECTORS) {
    assert.equal(pairingCode(token), expected, `token ${JSON.stringify(token)}`);
  }
});

test('the pairing alphabet cannot be read two ways', () => {
  const codes = PAIRING_VECTORS.map(([t]) => pairingCode(t)).join('');
  for (const ambiguous of ['0', 'O', '1', 'I', 'L', 'U']) {
    assert.ok(!codes.includes(ambiguous), `${ambiguous} is ambiguous read aloud`);
  }
  assert.match(pairingCode('anything'), /^[A-Z2-9]{3}-[A-Z2-9]{3}$/);
});

test('sha256Hex matches the server hash the store is keyed on', () => {
  // echo -n "" | shasum -a 256
  assert.equal(
    sha256Hex(''),
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  );
});

test('secrets have the shape the agent and server both validate', () => {
  for (let i = 0; i < 32; i++) {
    const s = newSecret();
    // The agent's claim endpoint validates 20..=100; the server mints 43.
    assert.equal(s.length, 43);
    assert.match(s, /^[A-Za-z0-9_-]+$/, 'base64url, so it survives a URL fragment');
  }
  assert.notEqual(newSecret(), newSecret());
});

/* ── staleness: the spool-replay guard ──────────────────────────────── */

const at = (iso) => ({ collectedAt: iso });

test('a reading older than the stored one is stale', () => {
  assert.equal(isStale(at('2026-08-24T10:00:00Z'), at('2026-08-24T11:00:00Z'), null), true);
});

test('a reading newer than the stored one is not stale', () => {
  assert.equal(isStale(at('2026-08-24T12:00:00Z'), at('2026-08-24T11:00:00Z'), null), false);
});

test('a replayed duplicate of the stored reading is stale', () => {
  const same = '2026-08-24T11:00:00Z';
  assert.equal(isStale(at(same), at(same), null), true);
});

test('the first reading a machine ever sends is never stale', () => {
  assert.equal(isStale(at('2026-08-24T10:00:00Z'), null, null), false);
});

test('an unparseable timestamp is not treated as stale', () => {
  // Refusing the reading would lose data over a clock the agent formats; the
  // failure mode of accepting it is a reordered panel, not a silent gap.
  assert.equal(isStale(at('not a date'), at('2026-08-24T11:00:00Z'), null), false);
  assert.equal(isStale(at('2026-08-24T11:00:00Z'), {}, null), false);
});

test('lastSeenAt stands in when the stored snapshot has no timestamp', () => {
  assert.equal(isStale(at('2026-08-24T10:00:00Z'), {}, '2026-08-24T11:00:00Z'), true);
});

/* ── endings: what stopped between two readings ─────────────────────── */

const proc = (pid, cmd, elapsed = '00:05:00') => ({
  pid, cmd, tool: 'claude-code', kind: 'interactive', elapsed,
});
const snapWith = (procs, collectedAt = '2026-08-24T11:00:00Z') => ({
  collectedAt, metrics: { processes: procs },
});

test('a process gone from the next reading has ended', () => {
  const prev = snapWith([proc(1, 'claude a'), proc(2, 'claude b')], '2026-08-24T10:59:30Z');
  const cur = snapWith([proc(1, 'claude a')]);
  const out = diffEndings(prev, [], 'workbench', null, cur, '2026-08-24T11:00:00Z');
  assert.equal(out.length, 1);
  assert.equal(out[0].pid, 2);
  assert.equal(out[0].host, 'workbench');
  assert.equal(out[0].ran_seconds, 300);
  // Both timestamps, because the truth is a window, not an instant.
  assert.equal(out[0].last_seen, '2026-08-24T10:59:30Z');
  assert.equal(out[0].noticed_at, '2026-08-24T11:00:00Z');
});

test('a process still running has not ended', () => {
  const prev = snapWith([proc(1, 'claude a')]);
  const cur = snapWith([proc(1, 'claude a')]);
  assert.deepEqual(diffEndings(prev, [], 'w', null, cur, 'now'), []);
});

test('the first reading ends nothing', () => {
  const cur = snapWith([proc(1, 'claude a')]);
  assert.deepEqual(diffEndings(null, [], 'w', null, cur, 'now'), []);
});

test('endings accumulate newest-first and stay bounded at 40', () => {
  const kept = Array.from({ length: 40 }, (_, i) => ({ pid: 1000 + i }));
  const prev = snapWith([proc(7, 'claude gone')]);
  const out = diffEndings(prev, kept, 'w', null, snapWith([]), 'now');
  assert.equal(out.length, 40);
  assert.equal(out[0].pid, 7, 'the new ending leads');
  assert.equal(out[39].pid, 1038, 'the oldest fell off the end');
});

test('etime parses every ps shape the agent can send', () => {
  assert.equal(etimeSeconds('00:30'), 30);
  assert.equal(etimeSeconds('05:00'), 300);
  assert.equal(etimeSeconds('01:00:00'), 3600);
  assert.equal(etimeSeconds('2-03:04:05'), 2 * 86400 + 3 * 3600 + 4 * 60 + 5);
  assert.equal(etimeSeconds('nonsense'), null);
  assert.equal(etimeSeconds(undefined), null);
});

/* ── the size trim ──────────────────────────────────────────────────── */

test('a snapshot within budget is untouched and unmarked', () => {
  const snap = { metrics: { usage: { sessions: [1, 2, 3] } } };
  const out = trimToBudget(snap, 10_000);
  assert.deepEqual(out.metrics.usage.sessions, [1, 2, 3]);
  assert.equal(out.trimmed, undefined);
});

test('an oversized snapshot sheds sessions first and says it was trimmed', () => {
  const snap = {
    metrics: {
      usage: { sessions: Array.from({ length: 400 }, (_, i) => ({ id: 's'.repeat(50) + i })) },
      claude: { daily: [{ date: '2026-08-24' }] },
    },
  };
  const out = trimToBudget(snap, 2_000);
  assert.equal(out.trimmed, true);
  assert.equal(out.metrics.usage.sessions, undefined);
  assert.deepEqual(out.metrics.claude.daily, [{ date: '2026-08-24' }], 'cheaper sections survive');
});

test('trimming keeps going until it fits, not just one pass', () => {
  const fat = (n) => Array.from({ length: n }, (_, i) => ({ v: 'x'.repeat(80) + i }));
  const snap = {
    metrics: {
      usage: { sessions: fat(200), tools: { byTool: fat(200) } },
      prompts: fat(200),
      governance: { rules: fat(200) },
      codex: { sessions: fat(200) },
      claude: { daily: fat(200) },
    },
  };
  const out = trimToBudget(snap, 1_500);
  assert.ok(JSON.stringify(out).length <= 1_500, 'fits the budget it was given');
  assert.equal(out.trimmed, true);
});

/* ── packing: the reason a heartbeat is affordable ──────────────────── */

test('a reading survives being packed and unpacked exactly', () => {
  const snap = {
    host: 'workbench',
    collectedAt: '2026-08-24T11:00:00Z',
    // 1.1400000000000001 is the value the naive JSON parser produces for 1.14,
    // and the agent and the Rust server both go out of their way to round-trip
    // it correctly. A store that quietly changed it would undo that.
    metrics: { usage: { allTime: { estUSD: 1.14 } }, processes: [{ pid: 1, cmd: 'claude' }] },
  };
  assert.deepEqual(unpackSnapshot(packSnapshot(structuredClone(snap))), snap);
});

test('packing is what makes a reading small enough to be cheap', () => {
  // Readings are deeply repetitive, which is the property the write cost turns
  // on: a measured 94 KB reading packs to about 26 KB, and DynamoDB charges by
  // the kilobyte written.
  const day = (i) => ({ date: `2026-06-${String((i % 28) + 1).padStart(2, '0')}`, tokens: 1e6 + i, estUSD: 1.5, sessions: 3, toolCalls: 40, messages: 12 });
  const snap = { metrics: { claude: { daily: Array.from({ length: 300 }, (_, i) => day(i)) } } };
  const raw = JSON.stringify(snap).length;
  const packed = packSnapshot(snap).length;
  assert.ok(packed < raw / 4, `packed ${packed} should be far under raw ${raw}`);
});

test('a reading too big to pack is trimmed until it fits, and says so', () => {
  const fat = (n) => Array.from({ length: n }, (_, i) => ({ v: `${Math.random()}`.repeat(20) + i }));
  const snap = {
    metrics: {
      usage: { sessions: fat(400), tools: { byTool: fat(400) } },
      prompts: fat(400),
      governance: { rules: fat(400) },
      codex: { sessions: fat(400) },
      claude: { daily: fat(400) },
    },
  };
  const packed = packSnapshot(snap, 4_000);
  assert.ok(packed.length <= 4_000, `packed ${packed.length} fits the budget it was given`);
  assert.equal(unpackSnapshot(packed).trimmed, true);
});

test('an unreadable stored reading is null, not an exception', () => {
  // One corrupt row must not take down a board that has four other machines
  // on it.
  for (const bad of [null, undefined, '', 'not base64 gzip', 'AAAA']) {
    assert.equal(unpackSnapshot(bad), null);
  }
});

/* ── what the next heartbeat has to remember ────────────────────────── */

test('previousOf keeps exactly what the next diff reads, and nothing else', () => {
  const snap = {
    collectedAt: '2026-08-24T11:00:00Z',
    host: 'workbench',
    metrics: {
      processes: [{ pid: 1, cmd: 'claude', tool: 'claude-code', elapsed: '00:05:00' }],
      usage: { sessions: Array.from({ length: 500 }, (_, i) => i) },
    },
  };
  const prev = previousOf(snap);
  assert.deepEqual(Object.keys(prev).sort(), ['collectedAt', 'metrics']);
  assert.deepEqual(Object.keys(prev.metrics), ['processes']);
  assert.equal(prev.collectedAt, '2026-08-24T11:00:00Z');
  assert.ok(JSON.stringify(prev).length < 200, 'the expensive half did not come along');
});

test('the stub previousOf leaves behind still drives the two things that read it', () => {
  const first = { collectedAt: '2026-08-24T10:59:30Z', metrics: { processes: [{ pid: 2, cmd: 'claude b', tool: 'claude-code', elapsed: '00:05:00' }] } };
  const second = { collectedAt: '2026-08-24T11:00:00Z', metrics: { processes: [] } };
  const stub = previousOf(first);

  assert.equal(isStale(second, stub, null), false, 'a newer reading is not stale against the stub');
  assert.equal(isStale(first, stub, null), true, 'a replay of the stored reading is');

  const ended = diffEndings(stub, [], 'workbench', null, second, '2026-08-24T11:00:00Z');
  assert.equal(ended.length, 1);
  assert.equal(ended[0].pid, 2);
  assert.equal(ended[0].ran_seconds, 300);
  assert.equal(ended[0].last_seen, '2026-08-24T10:59:30Z');
});

test('previousOf survives a reading with no processes at all', () => {
  assert.deepEqual(previousOf({}), { collectedAt: null, metrics: { processes: [] } });
  assert.deepEqual(previousOf(null), { collectedAt: null, metrics: { processes: [] } });
});
